Spotify api
ashley7295/Artist_Obsessed pull request #14
Opened 2020-10-15 02:08 UTC by ashley7295

Spotify API will still need to be adjusted as more features are added to the program but it is successfully returning the follower count of an artist. You can retrieve the Client_ID and Client Secret from [https://developer.spotify.com/dashboard/](url) and by creating an account.

2020-10-16 16:03 UTC, yp0975eu commented
@ashley7295 , you migh needs to merge master into your branch, then re-push so that you can resolve any conflicts.

2020-10-16 16:03 UTC, yp0975eu requested changes
I've added a few suggestions.

2020-10-16 16:03 UTC, yp0975eu commented on spotifyAPI.py
> +
Line 40 - 46 only needs to happen once on init.
Init could set the b64 encoded string as a variable when initialized and get_client_credentials can return the variable

2020-10-16 16:03 UTC, yp0975eu commented on spotifyAPI.py
> +    def get_user_search_q(self):
SpotifyAPI class should not be concerned with I/O operations. I would remove this method altogether.

2020-10-16 16:03 UTC, yp0975eu commented on spotifyAPI.py
> +        data = urlencode({'q':querie, 'type':querie_type}) #using urlencode to make it a url ready string
requests module will encode url parameters for you. There's no need to encode them here.

2020-10-16 16:03 UTC, yp0975eu commented on spotifyAPI.py
> +        lookup_url = f'{endpoint}?{data}'
Requests takes a url, and params named argument.  On this line you re constructing a url with query parameter data. Requests module will do this for you.

```
endpoint = https://api.spotify.com/v1/search
params = {'q':querie, 'type':querie_type}
requests.get(endpoint, params=params)
```

2020-10-16 18:29 UTC, yp0975eu requested changes
spelling mistake

2020-10-16 18:29 UTC, yp0975eu commented on spotifyAPI.py
> +    def search_artist_data(self, querie):
I think `querie` is spelled with a `y`.  `querie`  -> `query`

2020-10-21 01:25 UTC, ashley7295 commented on spotifyAPI.py
> +
Issue here is resolved as your suggestion works with python 2.0 but not with python 3.8. Program uses Python 3.8.2.

2020-10-21 01:29 UTC, ashley7295 commented on spotifyAPI.py
> +        data = urlencode({'q':querie, 'type':querie_type}) #using urlencode to make it a url ready string
resolved issue with in person code review. 'data' value will be encoded in requests. 

       data = {'q':query,'type':querie_type}
        lookup_url = f'{endpoint}'
        r = requests.get(lookup_url,headers=headers, params = data)
        followers = r.json()

2020-10-21 01:30 UTC, ashley7295 commented
Adjusted all code review, leaving open for further review as per request

2020-10-23 00:03 UTC, yp0975eu approved these changes

2020-10-23 00:12 UTC, jy8474np commented
Zoom code review. In progress code looks good. Still needs testing and validation.

2020-10-23 01:45 UTC, merged